/**
 * 隐私政策与使用条款正文（中 / 英 / 匈），按当前语言注入到 privacy.html、terms.html
 */
(function () {
  var L = window.LEGAL_PAGES = { privacy: {}, terms: {} };

  // ---------- 隐私政策 Privacy Policy ----------
  L.privacy.zh = '<section><h2>1. 适用范围</h2><p>本隐私政策适用于本网站及相关功能，包括房源浏览、账户注册与登录、发布和编辑房源、图片上传、收藏、搜索筛选以及联系页面等。访问或使用本平台，即表示您理解本政策所描述的数据处理方式。</p></section>' +
    '<section><h2>2. 我们会收集哪些信息</h2><p>为了提供房产平台服务，我们可能会收集以下信息：</p><ul><li>账户信息：例如姓名、邮箱、登录凭证等。密码不会以明文方式保存。</li><li>房源信息：例如标题、简介、详细描述、区份、位置、价格、面积、房屋类型、配套信息、图片以及您主动填写的其他内容。</li><li>设备和访问数据：例如浏览器类型、访问时间、请求日志、页面操作记录等基础技术信息，用于安全与稳定运行。</li><li>本地设备数据：例如语言选择、收藏记录、部分页面状态或临时房源数据，这些内容可能保存在您的浏览器本地存储中。</li><li>会话信息：为保持登录状态与账户安全，平台可能使用会话 Cookie 或类似技术。</li></ul></section>' +
    '<section><h2>3. 哪些信息会公开显示</h2><p>当您发布房源时，您提交的部分内容会向其他访客公开展示，包括但不限于房源标题、价格、区域、位置描述、房屋参数、配套信息、图片和房源正文。请勿在公开字段中填写身份证号、银行卡信息、精确隐私住址、密码或其他敏感个人信息。</p></section>' +
    '<section><h2>4. 我们如何使用这些信息</h2><ul><li>创建和管理用户账户，支持登录、退出、身份识别与安全校验。</li><li>展示、搜索、排序、筛选和管理房源内容。</li><li>处理图片上传、房源编辑、删除与发布状态更新。</li><li>维护平台正常运行，防止滥用、欺诈、垃圾信息和未经授权的访问。</li><li>改进用户体验，例如记住语言偏好、收藏状态和部分页面设置。</li><li>在符合法律要求的前提下，处理用户请求、投诉或合规事务。</li></ul></section>' +
    '<section><h2>5. 数据处理依据</h2><p>我们处理个人数据的依据通常包括：为向您提供平台服务而履行必要义务、维护平台安全与正常运营的正当利益、遵守适用法律法规，以及在适用情况下基于您的授权或主动提交。</p></section>' +
    '<section><h2>6. 数据共享与披露</h2><p>我们不会将您的个人信息出售给第三方。仅在以下情形下，相关信息可能被提供或披露：</p><ul><li>为完成网站托管、存储、技术维护或安全服务所必需的服务支持方。</li><li>根据法律法规、监管机关、法院或执法部门的合法要求。</li><li>为保护平台、用户或公众的合法权益所必要的情形。</li><li>您主动选择公开发布的房源内容，本身即会向平台访客展示。</li></ul></section>' +
    '<section><h2>7. 数据保存期限</h2><ul><li>账户信息：通常在账户存续期间保存，并在合理期限内保留必要记录以满足安全、审计或合规要求。</li><li>房源信息：在房源展示期间保存；当您删除房源或平台下架后，平台可能在合理备份周期内继续保留副本。</li><li>技术日志：通常仅在安全、排障和运行维护所需的合理期间内保留。</li><li>浏览器本地存储：由您的设备保留，您可通过浏览器设置自行清除。</li></ul></section>' +
    '<section><h2>8. 您的权利</h2><p>在适用法律允许的范围内，您可就个人数据提出以下请求：</p><ul><li>查询我们是否持有您的信息以及信息的处理方式。</li><li>更正不准确或不完整的信息。</li><li>删除账户或要求删除不再必要的数据。</li><li>反对或限制特定处理活动。</li><li>撤回基于授权进行的数据处理（如适用）。</li></ul><p>如需行使上述权利，请通过网站联系页面与我们联系。为保护账户安全，我们可能要求您先完成身份核验。</p></section>' +
    '<section><h2>9. 安全措施</h2><p>我们会采取合理的管理、技术和组织措施保护您的数据，降低未授权访问、篡改、丢失或泄露的风险。但互联网传输和电子存储无法保证绝对安全，因此请您同时妥善保管自己的登录信息与设备。</p></section>' +
    '<section><h2>10. 未成年人</h2><p>本平台主要面向具备民事行为能力的用户。若未成年人使用本平台，应在监护人知情并同意的情况下进行，且不应提交不必要的个人信息或敏感材料。</p></section>' +
    '<section><h2>11. 政策更新</h2><p>我们可能根据业务变化、功能调整或法律要求更新本隐私政策。更新后的版本将在本页面公布，并以页面标注的“最后更新”日期为准。</p></section>' +
    '<section><h2>12. 联系方式</h2><p>如果您对本隐私政策、数据处理方式或个人信息权利行使有任何疑问，请通过网站现有联系页面或平台内可用联系方式与我们联系。</p></section>' +
    '<section><h2>13. 说明</h2><p>本页面内容为适用于本平台业务场景的原创政策文本，用于平台规则说明与用户告知，不应被理解为针对具体个案的律师法律意见。如您需要正式的法律合规审查，建议再由当地专业律师进行复核。</p></section>';

  L.privacy.en = '<section><h2>1. Scope</h2><p>This privacy policy applies to this website and its features, including property browsing, account registration and login, listing and editing properties, image uploads, favourites, search and filters, and contact pages. By accessing or using the platform, you acknowledge the data practices described in this policy.</p></section>' +
    '<section><h2>2. Information we collect</h2><p>To provide the property platform service, we may collect:</p><ul><li>Account information: e.g. name, email, login credentials. Passwords are not stored in plain text.</li><li>Listing information: e.g. title, summary, description, district, location, price, area, property type, amenities, images and other content you provide.</li><li>Device and access data: e.g. browser type, visit time, request logs and basic technical data for security and stability.</li><li>Local device data: e.g. language preference, saved favourites, and some page state or temporary listing data, which may be stored in your browser.</li><li>Session information: we may use session cookies or similar technology to maintain login state and account security.</li></ul></section>' +
    '<section><h2>3. What is shown publicly</h2><p>When you publish a listing, some of the content you submit is shown to other visitors, including but not limited to title, price, area, location, parameters, amenities, images and description. Do not enter ID numbers, payment details, precise private addresses, passwords or other sensitive data in public fields.</p></section>' +
    '<section><h2>4. How we use this information</h2><ul><li>Create and manage user accounts, support login, logout, identification and security checks.</li><li>Display, search, sort, filter and manage listing content.</li><li>Process image uploads, listing edits, deletion and publishing.</li><li>Maintain normal operation and prevent abuse, fraud, spam and unauthorised access.</li><li>Improve user experience, e.g. remembering language preference, favourites and settings.</li><li>Handle user requests, complaints or compliance where required by law.</li></ul></section>' +
    '<section><h2>5. Legal basis</h2><p>We process personal data on the basis of: performing the contract to provide the service, legitimate interests in security and operation, compliance with applicable law, and where applicable your consent or the data you voluntarily provide.</p></section>' +
    '<section><h2>6. Sharing and disclosure</h2><p>We do not sell your personal information. We may share or disclose it only: to service providers necessary for hosting, storage, maintenance or security; when required by law, regulators, courts or authorities; to protect the platform, users or the public; or where you have chosen to publish listing content to visitors.</p></section>' +
    '<section><h2>7. Retention</h2><ul><li>Account data: generally kept while the account exists and for a reasonable period for security, audit or compliance.</li><li>Listing data: kept while the listing is active; after removal we may retain copies for a reasonable backup period.</li><li>Technical logs: kept only as long as needed for security and operation.</li><li>Browser storage: controlled by your device; you can clear it in your browser settings.</li></ul></section>' +
    '<section><h2>8. Your rights</h2><p>Where the law allows, you may request: to know whether we hold your data and how it is processed; correction of inaccurate or incomplete data; deletion of your account or unnecessary data; to object to or restrict certain processing; to withdraw consent where processing is based on consent. To exercise these rights, contact us via the website contact page. We may ask you to verify your identity first.</p></section>' +
    '<section><h2>9. Security</h2><p>We take reasonable technical and organisational measures to protect your data against unauthorised access, alteration, loss or disclosure. The internet and electronic storage cannot be guaranteed completely secure; please also keep your login details and device safe.</p></section>' +
    '<section><h2>10. Minors</h2><p>This platform is mainly for users with legal capacity. If a minor uses it, this should be with a guardian\'s knowledge and consent, and they should not submit unnecessary personal or sensitive data.</p></section>' +
    '<section><h2>11. Updates</h2><p>We may update this policy due to business or legal changes. The updated version will be published on this page; the "Last updated" date applies.</p></section>' +
    '<section><h2>12. Contact</h2><p>If you have questions about this privacy policy or your data, contact us via the website contact page or other available means.</p></section>' +
    '<section><h2>13. Note</h2><p>This text is for platform rules and user information only and does not constitute legal advice. For formal legal or compliance review, please consult a local lawyer.</p></section>';

  L.privacy.hu = '<section><h2>1. Hatály</h2><p>Ez az adatvédelmi szabályzat a weboldalra és funkcióira vonatkozik: ingatlan böngészés, regisztráció, bejelentkezés, hirdetésfeladás és szerkesztés, képfeltöltés, kedvencek, keresés és szűrés, kapcsolat. Az oldal használatával Ön elfogadja az itt leírt adatkezelést.</p></section>' +
    '<section><h2>2. Gyűjtött adatok</h2><p>A szolgáltatás nyújtásához az alábbi adatokat gyűjthetjük: fiókadatok (név, e-mail, belépési adatok; a jelszó nem tárolódik nyíltan); hirdetésadatok (cím, leírás, hely, ár, terület, típus, képek stb.); eszköz- és látogatási adatok; helyi adatok (nyelv, kedvencek); munkamenet (cookie) a bejelentkezéshez.</p></section>' +
    '<section><h2>3. Nyilvános megjelenítés</h2><p>Hirdetés feladásakor a megadott tartalom egy része nyilvánosan látható (cím, ár, hely, paraméterek, képek, leírás). Ne adjon meg nyilvános mezőkben személyigazolvány-, bank- vagy jelszóadatokat.</p></section>' +
    '<section><h2>4. Adatfelhasználás</h2><p>Fő célok: fiókkezelés, bejelentkezés, hirdetések megjelenítése és kezelése, képek feltöltése, platform biztonság, visszaélések megelőzése, felhasználói élmény (nyelv, kedvencek), jogi kérések kezelése.</p></section>' +
    '<section><h2>5. Jogalap</h2><p>Az adatkezelés jogalapja: szerződés teljesítése, jogos érdek, jogszabályi kötelezettség, illetve Ön önkéntes megadása vagy hozzájárulása.</p></section>' +
    '<section><h2>6. Megosztás</h2><p>Személyes adatokat nem értékesítünk. Csak szükséges szolgáltatóknak, jogszabályi kérésre, a platform vagy felhasználók védelmében, vagy nyilvánosan megjelent hirdetés esetén oszthatunk meg adatokat.</p></section>' +
    '<section><h2>7. Megtartás</h2><p>Fiókadatok: a fiók fennállása alatt; hirdetésadatok: a hirdetés aktív idején, törlés után rövid ideig tartalék; technikai naplók: szükséges ideig; böngésző: Ön törölheti a beállításokban.</p></section>' +
    '<section><h2>8. Joga Önnek</h2><p>Jogosult tájékoztatásra, helyesbítésre, törlésre, tiltakozásra, korlátozásra, a hozzájárulás visszavonására – a jogszabályoknak megfelelően. Kérést a kapcsolat felületen tehet.</p></section>' +
    '<section><h2>9. Biztonság</h2><p>Ésszerű technikai és szervezeti intézkedésekkel védjük az adatokat. Az internetes adatátvitel nem mindig 100%-osan biztonságos; Ön is őrizze jelszavát és eszközét.</p></section>' +
    '<section><h2>10. Kiskorúak</h2><p>A platform főleg teljes cselekvőképességű felhasználóknak szól. Kiskorú használata gondviselői hozzájárulással történjen, és ne adjon meg feleslegesen személyes adatokat.</p></section>' +
    '<section><h2>11. Frissítések</h2><p>A szabályzatot üzleti vagy jogi okokból módosíthatjuk. A friss verzió ezen az oldalon jelenik meg; a „Utoljára frissítve” dátum érvényes.</p></section>' +
    '<section><h2>12. Kapcsolat</h2><p>Az adatvédelmi kérdésekkel kapcsolatban a weboldal kapcsolat felületén vagy egyéb elérhetőségen keresztül fordulhat hozzánk.</p></section>' +
    '<section><h2>13. Megjegyzés</h2><p>Ez a szöveg csak tájékoztató jellegű, nem minősül jogi tanácsadásnak. Formális jogi ellenőrzéshez kérjük konzultáljon helyi ügyvéddel.</p></section>';

  // ---------- 使用条款 Terms of Use ----------
  L.terms.zh = '<section><h2>1. 接受条款</h2><p>访问、注册或使用本平台，即表示您同意遵守本使用条款及平台相关规则。如果您不同意本条款，请停止使用本平台。</p></section>' +
    '<section><h2>2. 平台服务性质</h2><p>本平台是房源信息展示、搜索和发布平台，主要提供房产信息浏览、账户管理、房源发布、图片展示及相关辅助功能。除非页面中明确另有说明，本平台不当然构成中介、估值、法律、税务或金融意见提供方，也不自动成为任一房产交易的合同当事人。</p></section>' +
    '<section><h2>3. 账户注册与安全</h2><ul><li>您应提供真实、完整且可联系的信息注册和使用账户。</li><li>您应自行妥善保管登录凭证，并对账户项下发生的操作负责。</li><li>如发现账户被盗用、异常登录或其他安全问题，您应及时通知平台并修改密码。</li><li>您不得冒用他人身份、伪造发布主体或绕过平台的安全限制。</li></ul></section>' +
    '<section><h2>4. 房源发布规则</h2><p>发布房源时，您承诺对所提交内容拥有合法权利，并保证内容真实、合法、完整且不过度误导。您提交的信息包括但不限于标题、价格、位置、房屋参数、配套信息、描述和图片。</p><ul><li>不得发布虚假房源、已成交仍冒充在售房源、恶意重复房源或明显误导性内容。</li><li>不得发布侵犯他人隐私、肖像权、著作权、商标权或其他合法权益的内容。</li><li>不得上传违法、欺诈、侮辱、骚扰、政治煽动、恶意营销、垃圾信息或与房产服务明显无关的内容。</li><li>不得在房源公开内容中泄露不必要的敏感个人信息。</li></ul></section>' +
    '<section><h2>5. 图片与内容授权</h2><p>您保留自己上传内容的权利，但在向本平台提交房源、图片和文本时，授予本平台为展示、存储、排版、缩略图生成、搜索呈现、页面缓存和正常运营所必需的非独占使用权。您应确保上传内容不侵犯第三方权利。</p></section>' +
    '<section><h2>6. 搜索与筛选结果说明</h2><p>平台会根据您设置的搜索条件、排序方式和房源字段生成搜索结果。平台会尽量保证结果与当前数据一致，但搜索结果仍受房源发布者填写内容、数据更新时间、浏览器缓存或临时技术异常影响。搜索结果仅作为信息展示，不应被理解为平台对房源真实性、价值、产权状态或交易成功的保证。</p></section>' +
    '<section><h2>7. 用户行为限制</h2><ul><li>不得使用自动化手段恶意抓取、批量复制、刷接口、压测或破坏平台稳定性。</li><li>不得尝试未经授权访问后台、他人账户、未公开接口或受限制资源。</li><li>不得传播恶意代码、木马、病毒、广告脚本或其他可能危害平台和用户的内容。</li><li>不得利用平台实施欺诈、钓鱼、洗钱、非法集资或其他违法活动。</li></ul></section>' +
    '<section><h2>8. 平台的审核与处置权</h2><p>为维护平台秩序和用户体验，平台有权在不事先通知的情况下，对涉嫌违规、重复、虚假、侵权、违法或存在明显风险的账户、房源、图片和其他内容进行审核、屏蔽、下架、限制展示、拒绝发布或删除处理。</p></section>' +
    '<section><h2>9. 费用与功能调整</h2><p>除非平台页面另有明确说明，当前提供的相关功能可免费使用。平台可根据产品规划、运营策略或合规要求调整功能、展示方式、可用范围或收费模式，并在适当位置进行说明。</p></section>' +
    '<section><h2>10. 第三方链接与外部内容</h2><p>平台部分页面可能包含跳转链接或与第三方服务相关的内容。对于第三方页面、第三方服务规则及其信息处理方式，平台不承担当然责任，用户应自行判断并阅读对应规则。</p></section>' +
    '<section><h2>11. 免责声明与责任限制</h2><ul><li>平台按“现状”和“可用”原则提供服务，不对所有页面内容的持续可用性、完全准确性或绝对不中断作出承诺。</li><li>平台不对用户发布的每一条房源信息进行逐项实地核验，也不保证房源内容完全真实、完整、最新或适合特定交易目的。</li><li>因用户自身填写错误、账号管理不当、浏览器缓存、网络故障、第三方服务异常或不可抗力导致的损失，平台将在适用法律允许范围内承担有限责任。</li><li>平台不直接参与用户之间的房产交易、付款、交付、产权审核或谈判安排，相关风险应由交易双方自行评估。</li></ul></section>' +
    '<section><h2>12. 账户暂停与终止</h2><p>如用户违反本条款、发布明显违规内容、存在安全风险或法律风险，平台有权暂停、限制或终止其账户与相关内容的使用。用户也可停止使用本平台，并在适用情况下申请删除相关账户或房源内容。</p></section>' +
    '<section><h2>13. 条款更新</h2><p>平台可根据服务变化、功能调整或法律要求修改本使用条款。更新后的内容将在本页面公布，并自公布或页面注明日期起生效。您在条款更新后继续使用平台的，视为接受更新后的内容。</p></section>' +
    '<section><h2>14. 适用规则与争议处理</h2><p>与本平台使用有关的争议，双方应尽量先通过友好协商解决。如协商不成，可根据平台运营地及适用法律规则处理。若您需要正式法律意见，建议另行咨询专业律师。</p></section>' +
    '<section><h2>15. 联系方式</h2><p>如果您对本使用条款、房源规则、账户处置或平台内容管理有任何疑问，可通过网站现有联系页面或平台可用联系方式与我们联系。</p></section>' +
    '<section><h2>16. 说明</h2><p>本页面内容为针对本平台业务场景撰写的原创使用条款文本，用于平台规则说明与用户告知，不构成针对具体事实或个案的律师法律意见。正式上线前，如您希望用于商业运营，建议再由当地律师进行审阅。</p></section>';

  L.terms.en = '<section><h2>1. Acceptance</h2><p>By accessing, registering or using this platform you agree to these terms and the platform rules. If you do not agree, please stop using the platform.</p></section>' +
    '<section><h2>2. Nature of the service</h2><p>This platform is for displaying, searching and publishing property listings. It provides browsing, account management, listing and image display. Unless stated otherwise, it does not act as agent, valuer, or legal/tax/financial adviser, and is not a party to any property transaction.</p></section>' +
    '<section><h2>3. Account and security</h2><ul><li>You must provide true, complete and contactable information.</li><li>You are responsible for keeping your login details safe and for all activity under your account.</li><li>If you suspect unauthorised access, notify the platform and change your password.</li><li>Do not impersonate others or circumvent security measures.</li></ul></section>' +
    '<section><h2>4. Listing rules</h2><p>You must have the right to submit content and ensure it is true, lawful and not misleading. Do not post fake listings, sold properties as available, duplicate or misleading content; do not infringe privacy, portrait rights, copyright or other rights; do not upload illegal, fraudulent, abusive or off-topic content; do not expose unnecessary sensitive data in listings.</p></section>' +
    '<section><h2>5. Content licence</h2><p>You keep rights to your content but grant the platform a non-exclusive licence to display, store, format, thumbnail, search and cache it for operation. You must not infringe third-party rights.</p></section>' +
    '<section><h2>6. Search results</h2><p>Results are generated from your criteria and listing data. We aim for accuracy but results can be affected by user input, updates, cache or technical issues. Results are for information only and do not guarantee accuracy, value, title or transaction outcome.</p></section>' +
    '<section><h2>7. Conduct</h2><ul><li>Do not scrape, bulk copy, overload interfaces or disrupt the platform.</li><li>Do not access backend, other accounts or restricted resources without authorisation.</li><li>Do not distribute malware, viruses or harmful content.</li><li>Do not use the platform for fraud, phishing, money laundering or illegal activity.</li></ul></section>' +
    '<section><h2>8. Moderation</h2><p>The platform may, without prior notice, review, hide, remove or refuse content or accounts that appear to breach rules, are duplicate, false, infringing, illegal or risky.</p></section>' +
    '<section><h2>9. Fees and changes</h2><p>Unless stated otherwise, current features are free. We may change features, display or pricing and will communicate changes where appropriate.</p></section>' +
    '<section><h2>10. Third-party links</h2><p>Some pages may link to third-party content. We are not responsible for third-party sites, services or their data practices; users should read their terms.</p></section>' +
    '<section><h2>11. Disclaimer</h2><ul><li>We provide the service "as is"; we do not guarantee uninterrupted or error-free operation.</li><li>We do not verify every listing in person or guarantee that content is fully true, complete or up to date.</li><li>We have limited liability for loss due to user error, account misuse, cache, network, third-party failure or force majeure.</li><li>We are not a party to transactions, payments, delivery or title checks; users bear that risk.</li></ul></section>' +
    '<section><h2>12. Suspension and termination</h2><p>We may suspend or terminate accounts and content that breach terms or pose security or legal risk. You may stop using the platform and request account or content deletion where applicable.</p></section>' +
    '<section><h2>13. Changes to terms</h2><p>We may update these terms; the new version will be published on this page and effective from the stated date. Continued use means acceptance.</p></section>' +
    '<section><h2>14. Disputes and law</h2><p>Disputes should first be resolved by negotiation. Otherwise they will be governed by the platform\'s operating jurisdiction. For legal advice, consult a lawyer.</p></section>' +
    '<section><h2>15. Contact</h2><p>For questions about these terms, listing rules or content, contact us via the website contact page or other available means.</p></section>' +
    '<section><h2>16. Note</h2><p>This text is for platform rules and user information only and does not constitute legal advice. For commercial use, have it reviewed by a local lawyer.</p></section>';

  L.terms.hu = '<section><h2>1. Feltételek elfogadása</h2><p>Az oldal használatával Ön elfogadja a felhasználási feltételekét és a platform szabályait. Ha nem ért egyet, ne használja a szolgáltatást.</p></section>' +
    '<section><h2>2. A szolgáltatás jellege</h2><p>A platform ingatlanhirdetések megjelenítésére, keresésére és közzétételére szolgál. Nem ügynök, értékbecslő vagy jogi / adó / pénzügyi tanácsadó, és nem felel a konkrét ingatlanügyletekért.</p></section>' +
    '<section><h2>3. Fiók és biztonság</h2><ul><li>Valós, teljes és elérhető adatokat kell megadnia.</li><li>A belépési adatok őrzése és a fiók alatti tevékenység az Ön felelőssége.</li><li>Jogosulatlan hozzáférés gyanúja esetén értesítse a platformot és változtassa meg a jelszavát.</li><li>Ne használja más személyének adatait és ne kerülje a biztonsági intézkedéseket.</li></ul></section>' +
    '<section><h2>4. Hirdetési szabályok</h2><p>A feltöltött tartalommal kapcsolatban joga kell legyen; a tartalom valós, törvényes és nem megtévesztő legyen. Tilos hamis, már eladottnak jelölt, duplikált vagy megtévesztő hirdetés; mások magánszférájának, jogainak sértése; illegális, zaklató vagy irreleváns tartalom; érzékeny adatok nyilvános mezőkben.</p></section>' +
    '<section><h2>5. Tartalom engedély</h2><p>Ön megtartja a tartalom jogait, de nem kizárólagos jogot ad a platformnak a megjelenítésre, tárolásra, formázásra, bélyegkép készítésre és működéshez szükséges cache-elésre. Ne sértse harmadik felek jogait.</p></section>' +
    '<section><h2>6. Keresési eredmények</h2><p>Az eredmények a megadott feltételek és hirdetésadatok alapján készülnek. Pontosságra törekszünk, de az eredményeket befolyásolhatja a felhasználói kitöltés, frissítések, cache vagy technikai hiba. Az eredmények csak tájékoztató jellegűek.</p></section>' +
    '<section><h2>7. Magatartás</h2><ul><li>Nem szabad automatikusan másolni, túlterhelni a rendszert vagy megzavarni a platformot.</li><li>Nem szabad jogosulatlanul hozzáférni a háttérhez, más fiókokhoz vagy korlátozott erőforrásokhoz.</li><li>Nem szabad kártevőt, vírust vagy káros tartalmat terjeszteni.</li><li>A platformot nem használhatja csalásra, adathalászatra vagy illegális tevékenységre.</li></ul></section>' +
    '<section><h2>8. Moderálás</h2><p>A platform előzetes értesítés nélkül ellenőrizheti, elrejtheti, törölheti vagy elutasíthatja a szabályt sértő, ismétlődő, hamis vagy kockázatos tartalmat és fiókot.</p></section>' +
    '<section><h2>9. Díjak és változások</h2><p>Hacsak másként nem jelöljük, a jelenlegi funkciók ingyenesek. A funkciókat, megjelenítést vagy díjazást módosíthatjuk; a változásról tájékoztatunk.</p></section>' +
    '<section><h2>10. Harmadik fél linkek</h2><p>Egyes oldalak harmadik fél tartalomra linkelhetnek. A harmadik fél oldalaiért, szolgáltatásáért vagy adatkezeléséért nem felelősünk.</p></section>' +
    '<section><h2>11. Felelősség kizárása</h2><ul><li>A szolgáltatást „ahogy van” nyújtjuk; nem garantáljuk a megszakítás nélküli vagy hibamentes működést.</li><li>Nem ellenőrizzük egyenként minden hirdetést; nem garantáljuk a tartalom teljes valódiságát vagy naprakészségét.</li><li>Korlátolt felelősségünk van a felhasználói hiba, fiók visszaélés, cache, hálózat vagy vis maior miatti kárért.</li><li>Nem vagyunk az ügyletek, fizetések vagy jogellenőrzések felei; a kockázat a felhasználóé.</li></ul></section>' +
    '<section><h2>12. Felfüggesztés és megszüntetés</h2><p>A feltételek megsértése vagy biztonsági / jogi kockázat esetén felfüggesztjük vagy megszüntetjük a fiókot és a tartalmat. Ön bármikor abbahagyhatja a használatot és törölheti a fiókot vagy tartalmat.</p></section>' +
    '<section><h2>13. Feltételek módosítása</h2><p>A feltételeket módosíthatjuk; az új verzió ezen az oldalon jelenik meg és a megadott naptól hatályos. A további használat az elfogadást jelenti.</p></section>' +
    '<section><h2>14. Viták és jog</h2><p>A vitákat először egyeztetéssel kell megoldani. Egyébként a platform működési joghatósága és a vonatkozó jog alkalmazandó. Jogi tanácsért forduljon ügyvédhez.</p></section>' +
    '<section><h2>15. Kapcsolat</h2><p>A feltételek, hirdetési szabályok vagy tartalommal kapcsolatos kérdésekben a weboldal kapcsolat felületén vagy egyéb elérhetőségen keressen minket.</p></section>' +
    '<section><h2>16. Megjegyzés</h2><p>Ez a szöveg csak tájékoztató jellegű, nem minősül jogi tanácsadásnak. Kereskedelmi használat előtt kérjük helyi ügyvéddel ellenőrizze.</p></section>';
})();
